# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20160828_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
