# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20160908_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcommoninfo',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Contract', verbose_name='\u5408\u540c'),
        ),
    ]
