# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20160912_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcommoninfo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='assetcommoninfo',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
