# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20160912_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='asset_common_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.AssetCommonInfo'),
        ),
    ]
