# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20160912_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='manufatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Manufactory'),
        ),
    ]
