# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20160913_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactory',
            name='support_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u670d\u52a1\u7535\u8bdd'),
        ),
    ]
