# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20160913_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disk',
            old_name='common_asset_info',
            new_name='asset_common_info',
        ),
        migrations.RenameField(
            model_name='nic',
            old_name='common_asset_info',
            new_name='asset_common_info',
        ),
        migrations.RenameField(
            model_name='raidadaptor',
            old_name='common_asset_info',
            new_name='asset_common_info',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='common_asset_info',
            new_name='asset_common_info',
        ),
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u78c1\u76d8\u5bb9\u91cf(GB)'),
        ),
    ]
