# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20160913_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='approved_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u6279\u51c6\u65e5\u671f'),
        ),
    ]
