# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20160913_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcommoninfo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='assets.AssetTag'),
        ),
    ]
